### ISSUE TITLE
There is a dot

### ISSUE THREAD

**Issue by nobel6018** [puyuan/py-nanoid#15]
I don't know why nanoid make a string included dot(.)
for example 593uu.uC387.y

**Comment by puyuan** [comment]
@nobel6018  Can you give some example of how you call the generate function?  Are you passing in any custom alphabets?

**Comment by nobel6018** [comment]
I thought, nanoid returns only predefined characters. The input has dot. Nanoid doesn't treat dot and pass it output. I understood why there are dots.

**Comment by puyuan** [comment]
To generate predefined characters,  nothing needs to be passed in. Or if you want a different sized output, you can pass in the size parameter. 

But I think if you changed the alphabet, then that's probably what caused it.
