### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by priya-gitTest** [puyuan/py-nanoid#2]
print(generate(alphabet="12345a", size=3))
Traceback (most recent call last):
  File "E:/nanoid.py", line 33, in <module>
    print(generate(alphabet="12345a", size=3))
  File "E:/nanoid.py", line 26, in generate
    if alphabet[byte]:
IndexError: string index out of range

Process finished with exit code 1

**Comment by puyuan** [comment]
Thanks, I will review the PR.

**Comment by puyuan** [comment]
v0.3.0 fixes this issue.
